### ISSUE TITLE
KeyError: 'data'运行出错

### ISSUE THREAD

**Issue by chern91552** [ReaJason/WeiBo_SuperTopics#2]
Run python3 task.py <<EOF
获取个人信息
开始超话签到
获取每日积分
超话评论转发
指定超话打榜
Traceback (most recent call last):
  File "task.py", line 14, in <module>
    run()
  File "task.py", line 10, in run
    wei.daily_task(s, pick, sckey)
  File "/home/runner/work/WeiBo_SuperTopics/WeiBo_SuperTopics/api.py", line 860, in daily_task
    log.append(self.get_score_bang([topic for topic in topic_list if topic["topic_title"] == pick]))
  File "/home/runner/work/WeiBo_SuperTopics/WeiBo_SuperTopics/api.py", line 235, in get_score_bang
    topic_name = score_res.json()["data"]["topic_name"]
KeyError: 'data'
Error: Process completed with exit code 1.
请问如何让解决

**Comment by ReaJason** [comment]
可能是发生了这两种错误，暂还没有更新代码
![image](https://user-images.githubusercontent.com/48389642/96355970-d547b380-111a-11eb-88c5-7e0d90104fb3.png)

**Comment by chern91552** [comment]
s参数是抓包的GET /2/remind/unread_count?uid=****&c=weicoabroad&s=***这个吗

**Comment by ReaJason** [comment]
s是八个连续相同的，比如22222222 dddddddd，就是在url的一个参数里面，应该是的

**Comment by chern91552** [comment]
签到超话的时候一直报错KeyError: 'msg'，然后我取消了签到任务。还有每天都不会转发点赞，那几项都是0，不知道怎么回事

**Comment by ReaJason** [comment]
这个GitHub上容易异常，你可以试试我写的本地程序，https://reajason.top/2020/10/19/WeiBoSuperTopicsTool/

**Comment by chern91552** [comment]
感谢，可以用
