### ISSUE TITLE
请问本地工具里的select是什么功能，还有希望能部署到服务器上

### ISSUE THREAD

**Issue by Lucas-TY** [ReaJason/WeiBo_SuperTopics#3]

**Comment by ReaJason** [comment]
就是超话打榜的积分，select1就是打榜1分，select66就是打榜66分，最后去256就是对应全部积分，这四个选项对应的就是app里面打榜的四个选项。
关于部署到服务器上，暂时还没有服务器，之后学习一下会出一个的，由于微博检测IP的，异地登录容易异常，真的很麻烦......
