### ISSUE TITLE
微博超话工具2.0功能征集帖

### ISSUE THREAD

**Issue by ReaJason** [ReaJason/WeiBo_SuperTopics#7]
不知道大家有什么其他功能需求可以在此处提出一些建议，如果复杂的话可以附上自己的实现思路，感谢🌈

**Comment by Dududade** [comment]
现在的功能已经挺齐全了，唯一希望的是可以跳过登陆扫二维码这个东东

**Comment by ReaJason** [comment]
> 现在的功能已经挺齐全了，唯一希望的是可以跳过登陆扫二维码这个东东

收到🌹，不过现在微博登陆跳二维码基本难以实现了，之后考虑是以二维码登陆

**Comment by zhongwangninja** [comment]
建议功能：微博超话补签卡兑换

微博超话APP中能够使用 666 积分兑换一张补签卡，超话签到断签时用来补签。路径：超话 App->我->补签卡->兑换补签卡。


超话积分会过期，如果不打榜的话每个月 5 号会过期，使用工具每个月能够稳定拿到 1200, 1300+ 积分，兑换补签卡还是很实用的。
